package mp4

import (
	"bytes"
	"io/ioutil"
	"testing"

	"github.com/edgeware/mp4ff/bits"
)

func TestDecodeSR(t *testing.T) {
	inData, err := ioutil.ReadFile("testdata/1.m4s")
	if err != nil {
		t.Error(err)
	}
	sr := bits.NewFixedSliceReader(inData)
	decFile, err := DecodeFileSR(sr)
	if err != nil {
		t.Error(err)
	}
	sw := bits.NewFixedSliceWriter(len(inData))
	err = decFile.EncodeSW(sw)
	if err != nil {
		t.Error(err)
	}
	if !bytes.Equal(inData, sw.Bytes()) {
		t.Errorf("generated bytes differ from input")
	}
}

func BenchmarkDecodeSegmentSR(b *testing.B) {
	inData, err := ioutil.ReadFile("testdata/1.m4s")
	if err != nil {
		b.Error(err)
	}
	for i := 0; i < b.N; i++ {
		sr := bits.NewFixedSliceReader(inData)
		_, _ = DecodeFileSR(sr)
	}
}
