name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          only-new-issues: true

      - name: go-report-card
        uses: creekorful/goreportcard-action@v1.0
        with:
          only-new-issues: true

